#!/bin/bash

# Get the C file name from the variable $CFILE
CFILE="$CFILE"

# Get the output file name by replacing the .c extension with .s
OFILE="${CFILE%.c}.s"

# Generate the assembly code using the gcc compiler and save it in the output file
gcc -S "$CFILE" -o "$OFILE"
